package org.irods.jargon.metadatatemplate;

/**
 *
 * @author Mike Conway and Rick Skarbez
 */

/**
 *
 * ONLY USER MODE IS CURRENTLY SUPPORTED
 * <p/>
 * Will specify the data source(s) that will be used to populated the metadata
 * template.
 * <p/>
 * USER - Values must be provided by the user via a user interface<br/>
 * DRIVER - Values will be generated by the <code>driver</code><br/>
 * <code>driver</code>
 *
 */
public enum SourceEnum {

	USER, DRIVER

}
