/**
 *
 */
package org.irods.jargon.vircoll;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a user view of virtual collections of different types. This
 * includes not only virtual collections in the user home directory that they
 * use as their 'view' of the grid, but also temporary queries, as well as
 * globally defined virtual collections that a user should see in their view.
 * <p/>
 * As vc's evolve to these broader types, we'll use this class as the complete
 * summary of the different types
 *
 * @author Mike Conway - DICE
 *
 */
public class UserVirtualCollectionProfile {

	/**
	 * User name for this profile
	 */
	private String userName = "";
	/**
	 * Home zone that generated this profile
	 */
	private String homeZone = "";
	/**
	 * Virtual collections defined by the user and visible
	 */
	private List<AbstractVirtualCollection> userHomeCollections = new ArrayList<AbstractVirtualCollection>();

	/**
	 * Virtual collections defined by the user and currently not enabled.
	 * Virtual collection definitions might be parked in a holding area when a
	 * user does not want to see them in any view
	 */
	private List<AbstractVirtualCollection> disabledUserHomeCollections = new ArrayList<AbstractVirtualCollection>();

	/**
	 * Virtual collections that were generated by some interactive query tool,
	 * these are saved for a time, and eventually either moved into a permanent
	 * state or they age out
	 */
	private List<AbstractVirtualCollection> userRecentQueries = new ArrayList<AbstractVirtualCollection>();

	/**
	 * Virtual collections in the user view that are defined at the grid level.
	 * Currently these are always displayed for the user
	 */
	private List<AbstractVirtualCollection> gridDefinedCollections = new ArrayList<AbstractVirtualCollection>();

	/**
	 *
	 */
	public UserVirtualCollectionProfile() {
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(final String userName) {
		this.userName = userName;
	}

	public String getHomeZone() {
		return homeZone;
	}

	public void setHomeZone(final String homeZone) {
		this.homeZone = homeZone;
	}

	public List<AbstractVirtualCollection> getUserHomeCollections() {
		return userHomeCollections;
	}

	public void setUserHomeCollections(final List<AbstractVirtualCollection> userHomeCollections) {
		this.userHomeCollections = userHomeCollections;
	}

	public List<AbstractVirtualCollection> getUserRecentQueries() {
		return userRecentQueries;
	}

	public void setUserRecentQueries(final List<AbstractVirtualCollection> userRecentQueries) {
		this.userRecentQueries = userRecentQueries;
	}

	public List<AbstractVirtualCollection> getGridDefinedCollections() {
		return gridDefinedCollections;
	}

	public void setGridDefinedCollections(final List<AbstractVirtualCollection> gridDefinedCollections) {
		this.gridDefinedCollections = gridDefinedCollections;
	}

	public List<AbstractVirtualCollection> getDisabledUserHomeCollections() {
		return disabledUserHomeCollections;
	}

	public void setDisabledUserHomeCollections(final List<AbstractVirtualCollection> disabledUserHomeCollections) {
		this.disabledUserHomeCollections = disabledUserHomeCollections;
	}

}
