/*
 * Data Grid Search API
 * This is and extensible, pluggable search API for iRODS focused on pluggable Elastic Search indexes.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: mike.conway@nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.irods.jargon.extensions.exportplugin.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * IndexSchemaDescription
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-06T15:09:01.384Z[GMT]")
public class IndexSchemaDescription {
	@SerializedName("id")
	private String id = null;

	@SerializedName("name")
	private String name = null;

	@SerializedName("info")
	private String info = null;

	@SerializedName("version")
	private String version = null;

	public IndexSchemaDescription id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique identifier for this index type
	 * 
	 * @return id
	 **/
	@Schema(description = "Unique identifier for this index type")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public IndexSchemaDescription name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Display name for this index type
	 * 
	 * @return name
	 **/
	@Schema(description = "Display name for this index type")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public IndexSchemaDescription info(String info) {
		this.info = info;
		return this;
	}

	/**
	 * Documentation about this particular index type
	 * 
	 * @return info
	 **/
	@Schema(description = "Documentation about this particular index type")
	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public IndexSchemaDescription version(String version) {
		this.version = version;
		return this;
	}

	/**
	 * Version identifier for this endpoint, preferably in semantic versioning style
	 * 
	 * @return version
	 **/
	@Schema(description = "Version identifier for this endpoint, preferably in semantic versioning style")
	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		IndexSchemaDescription indexSchemaDescription = (IndexSchemaDescription) o;
		return Objects.equals(this.id, indexSchemaDescription.id)
				&& Objects.equals(this.name, indexSchemaDescription.name)
				&& Objects.equals(this.info, indexSchemaDescription.info)
				&& Objects.equals(this.version, indexSchemaDescription.version);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, info, version);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class IndexSchemaDescription {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    info: ").append(toIndentedString(info)).append("\n");
		sb.append("    version: ").append(toIndentedString(version)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
