/*
 * Data Grid Search API
 * This is and extensible, pluggable search API for iRODS focused on pluggable Elastic Search indexes.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: mike.conway@nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.irods.jargon.extensions.searchplugin.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Indexes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-06T15:09:01.384Z[GMT]")
public class Indexes {
	@SerializedName("id")
	private String id = null;

	@SerializedName("name")
	private String name = null;

	@SerializedName("info")
	private String info = null;

	@SerializedName("maintainer")
	private String maintainer = null;

	@SerializedName("contact_email")
	private String contactEmail = null;

	@SerializedName("indexes")
	private List<IndexSchemaDescription> indexes = null;

	public Indexes id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique id that identifies this particular endpoint. Multiple endpoints may be
	 * configured to create a search cluster to address distinct indexes
	 * 
	 * @return id
	 **/
	@Schema(description = "Unique id that identifies this particular endpoint. Multiple endpoints may be configured to create a search cluster to address distinct indexes")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Indexes name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Human readable, meaningful name for the search endpoint
	 * 
	 * @return name
	 **/
	@Schema(description = "Human readable, meaningful name for the search endpoint")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Indexes info(String info) {
		this.info = info;
		return this;
	}

	/**
	 * Documentation about the function of the endpoint
	 * 
	 * @return info
	 **/
	@Schema(description = "Documentation about the function of the endpoint")
	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Indexes maintainer(String maintainer) {
		this.maintainer = maintainer;
		return this;
	}

	/**
	 * Maintainer of the api
	 * 
	 * @return maintainer
	 **/
	@Schema(description = "Maintainer of the api")
	public String getMaintainer() {
		return maintainer;
	}

	public void setMaintainer(String maintainer) {
		this.maintainer = maintainer;
	}

	public Indexes contactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
		return this;
	}

	/**
	 * email address of a support contact
	 * 
	 * @return contactEmail
	 **/
	@Schema(description = "email address of a support contact")
	public String getContactEmail() {
		return contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public Indexes indexes(List<IndexSchemaDescription> indexes) {
		this.indexes = indexes;
		return this;
	}

	public Indexes addIndexesItem(IndexSchemaDescription indexesItem) {
		if (this.indexes == null) {
			this.indexes = new ArrayList<IndexSchemaDescription>();
		}
		this.indexes.add(indexesItem);
		return this;
	}

	/**
	 * individually addressable indexes supported by this endpoint
	 * 
	 * @return indexes
	 **/
	@Schema(description = "individually addressable indexes supported by this endpoint")
	public List<IndexSchemaDescription> getIndexes() {
		return indexes;
	}

	public void setIndexes(List<IndexSchemaDescription> indexes) {
		this.indexes = indexes;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Indexes indexes = (Indexes) o;
		return Objects.equals(this.id, indexes.id) && Objects.equals(this.name, indexes.name)
				&& Objects.equals(this.info, indexes.info) && Objects.equals(this.maintainer, indexes.maintainer)
				&& Objects.equals(this.contactEmail, indexes.contactEmail)
				&& Objects.equals(this.indexes, indexes.indexes);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, info, maintainer, contactEmail, indexes);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Indexes {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    info: ").append(toIndentedString(info)).append("\n");
		sb.append("    maintainer: ").append(toIndentedString(maintainer)).append("\n");
		sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
		sb.append("    indexes: ").append(toIndentedString(indexes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
