/*
 * Data Grid Search API
 * This is and extensible, pluggable search API for iRODS focused on pluggable Elastic Search indexes.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: mike.conway@nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.irods.jargon.extensions.searchplugin.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SearchAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-06T15:09:01.384Z[GMT]")
public class SearchAttributes {
	@SerializedName("id")
	private String id = null;

	@SerializedName("name")
	private String name = null;

	@SerializedName("info")
	private String info = null;

	@SerializedName("attributes")
	private List<IndexSearchAttributes> attributes = null;

	public SearchAttributes id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique identifier for this index type
	 * 
	 * @return id
	 **/
	@Schema(description = "Unique identifier for this index type")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SearchAttributes name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Display name for this index type
	 * 
	 * @return name
	 **/
	@Schema(description = "Display name for this index type")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public SearchAttributes info(String info) {
		this.info = info;
		return this;
	}

	/**
	 * Documentation about this particular index type
	 * 
	 * @return info
	 **/
	@Schema(description = "Documentation about this particular index type")
	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public SearchAttributes attributes(List<IndexSearchAttributes> attributes) {
		this.attributes = attributes;
		return this;
	}

	public SearchAttributes addAttributesItem(IndexSearchAttributes attributesItem) {
		if (this.attributes == null) {
			this.attributes = new ArrayList<IndexSearchAttributes>();
		}
		this.attributes.add(attributesItem);
		return this;
	}

	/**
	 * array of possible search attributes that can be used to support textual
	 * advanced search flags as well as query builder interfaces
	 * attribute-by-attribute
	 * 
	 * @return attributes
	 **/
	@Schema(description = "array of possible search attributes that can be used to support textual advanced search flags as well as query builder interfaces attribute-by-attribute")
	public List<IndexSearchAttributes> getAttributes() {
		return attributes;
	}

	public void setAttributes(List<IndexSearchAttributes> attributes) {
		this.attributes = attributes;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SearchAttributes searchAttributes = (SearchAttributes) o;
		return Objects.equals(this.id, searchAttributes.id) && Objects.equals(this.name, searchAttributes.name)
				&& Objects.equals(this.info, searchAttributes.info)
				&& Objects.equals(this.attributes, searchAttributes.attributes);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, info, attributes);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SearchAttributes {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    info: ").append(toIndentedString(info)).append("\n");
		sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
